### ISSUE TITLE
Ensure the LIDAR works

### ISSUE THREAD

**Issue by abarnes6** [SIU-Robotics/ros-misc#1]

**Comment by peyton-otey** [comment]
LIDAR sensor information (Unitree 4D Lidar):
- Model: L1 PM
- S/N: E11D10NCC7CCX

Documentation:
- [User Guide Link](https://unitree-website.oss-cn-hangzhou.aliyuncs.com/Lidar/L1%20Quike%20Start%20Guide_v1.0.pdf)
- [User Manual Link](https://oss-global-cdn.unitree.com/static/52b72f707b304d229d4321eea223738f.pdf)

**Comment by peyton-otey** [comment]
[Unilidar SDK - Github](https://github.com/unitreerobotics/unilidar_sdk)
[Unilidar Lidar ROS package - Github](https://github.com/unitreerobotics/unilidar_sdk/tree/main/unitree_lidar_ros/src/unitree_lidar_ros)
