### ISSUE TITLE
Display LIDAR with Rviz

### ISSUE THREAD

**Issue by abarnes6** [SIU-Robotics/ros-misc#3]

**Comment by peyton-otey** [comment]
**All Official Unitree 4D LiDAR L1 Software (Windows 64-bit only:)**

https://www.unitree.com/download/


**L1 3D Model**
- [Download](https://oss-global-cdn.unitree.com/Lidar/L1%203D%20Model.STEP)


**Software and SDK**

Unilidar Point Cloud Software
- [Download](https://oss-global-cdn.unitree.com/Lidar/Unilidar_v1.0.0.zip)

Unilidar SDK User Manual
- [Download](https://oss-global-cdn.unitree.com/Lidar/Unilidar%20SDK%20User%20Manual_v1.0.pdf)

Unilidar SDK Software Package
- [Download](https://oss-global-cdn.unitree.com/static/a42f75fdba044f8a9f73ba1972488027.zip)


**SLAM and DATA**

L1 observed point cloud data
- [Download](https://oss-global-cdn.unitree.com/static/unilidar-2023-09-22-12-42-04.zip)

Open Source SLAM Software Package
- [Download](https://oss-global-cdn.unitree.com/static/Point_LIO_Unilidar-v1.0.0.zip)

**Comment by peyton-otey** [comment]
**unitree_ros2 (Github):**

https://github.com/unitreerobotics/unitree_ros2

(NOTE: Replace all instances of "foxy" with "humble" during the installation process.)

**Comment by peyton-otey** [comment]
All unitree_ros2 steps up to "Connect to Unitree robot" have been completed on 601159 (Ubuntu 22.04 computer in Mailroom) so far.

**Comment by peyton-otey** [comment]
https://oss-global-cdn.unitree.com/Lidar/Unilidar%20SDK%20User%20Manual_v1.0.pdf

Running "example_lidar" worked after following the above instructions with the LiDAR connected to the Ubuntu 22.04 computer in the mailroom. This simply shows that the LiDAR can be used with Ubuntu 22.04 for data collection.

**Comment by peyton-otey** [comment]
Current issue:

These seem to be the instructions that must be followed for a topic named "/unildar/cloud" to exist:
https://github.com/unitreerobotics/unitree_ros2

This topic is needed before pointcloud data can be displayed in Rviz. After following the above instructions, replacing each instance of "foxy" with "humble", there were no errors, but "/unilidar/cloud" still does not show when running `ros2 topic list`.

**Comment by peyton-otey** [comment]
Hopefully not going down the wrong path:

https://github.com/unitreerobotics/point_lio_unilidar

**Comment by peyton-otey** [comment]
[This video](https://www.youtube.com/watch?v=ydALTdUagEQ) shows a Unitree 4D LiDAR L1 running and displaying pointcloud data in Rviz. The configuration settings shown could be useful.

**Comment by peyton-otey** [comment]
FINALLY I believe this is the link of truth:

https://github.com/unitreerobotics/unilidar_sdk/tree/main/unitree_lidar_ros2/src/unitree_lidar_ros2

**Comment by abarnes6** [comment]
https://discourse.ros.org/t/new-implementation-for-unitree-go-2-in-ros-2-humble/38465

**Comment by peyton-otey** [comment]
![Image](https://github.com/user-attachments/assets/e92a3660-1d14-442b-9628-ba6e43dcdd19)

**Comment by peyton-otey** [comment]
End-to-end instructions to **set up Ubuntu 22.04 computer with ROS2**, **install proper Unitree 4d LiDAR L1 driver**, then **visualize pointcloud data in Rviz2**:

1. Install [Ubuntu 22.04 LTS](https://releases.ubuntu.com/jammy/ubuntu-22.04.5-desktop-amd64.iso)

2. Establish Internet connection

3. In Ubuntu, run these commands in a terminal to install and automatically source ROS2:
```    
    locale  # check for UTF-8

    sudo apt update && sudo apt install locales

    sudo locale-gen en_US en_US.UTF-8

    sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

    export LANG=en_US.UTF-8

    locale  # verify settings

    sudo apt install software-properties-common

    sudo add-apt-repository universe

    sudo apt update && sudo apt install curl -y

    sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null

    sudo apt update

    sudo apt upgrade

    sudo apt install ros-humble-desktop

    sudo apt install ros-humble-ros-base

    sudo apt install ros-dev-tools

    source /opt/ros/humble/setup.bash

    echo "source /opt/ros/humble/setup.bash" >> .bashrc
```

4. Plug in the LiDAR (to power outlet and to the Ubuntu computer via USB)

5. Verify the LiDAR is connected by running `ls /dev/ttyUSB*`. The only output should be `/dev/ttyUSB0`.
- If no output, connect LiDAR to the computer.
- If >1 output listed, disconnect other USB devices (flashdrives, etc.)

6. Run the following commands in a terminal (the terminal should hang after running the last command):

```
    git clone https://github.com/unitreerobotics/unilidar_sdk.git

    cd unilidar_sdk/unitree_lidar_ros2

    colcon build

    source install/setup.bash

    ros2 launch unitree_lidar_ros2 launch.py
```

7. Open a new terminal and run `rviz2 -d src/unitree_lidar_ros2/rviz/view.rviz `. This should launch Rviz2.
 
8. Under "Global Options", change "Fixed Frame" from `map` to `unilidar_lidar`.
 
9. Click "Add" in the bottom left, then under `rviz_default_plugins`, select "PointCloud2" and press OK.

10. Under "Displays", expand "PointCloud2", then in the "Topic" field, type `/unilidar/cloud`. Pointcloud data should now be displaying in Rviz2.

**Comment by peyton-otey** [comment]
Assuming ROS2 is installed, the LiDAR driver is installed, and both are sourced and running on an Ubuntu 22.04 system:

1. Run `ros2 launch unitree_lidar_ros2 launch.py` in a terminal (the terminal should hang after running this command).
2. Open a new terminal and run `rviz2 -d src/unitree_lidar_ros2/rviz/view.rviz`. This should launch Rviz2.
3. Under "Global Options", change "Fixed Frame" from `map` to `unilidar_lidar`.
4. Click "Add" in the bottom left, then under `rviz_default_plugins`, select "PointCloud2" and press OK.
5. Under "Displays", expand "PointCloud2", then in the "Topic" field, type `/unilidar/cloud`. Pointcloud data should now be displaying in Rviz2.
