### ISSUE TITLE
Create URDF of the bot

### ISSUE THREAD

**Issue by abarnes6** [SIU-Robotics/ros-misc#5]
URDF of the bot to be used with Gazebo

**Comment by JaredHillyer** [comment]
Urdf is an XML language that can be parameterized with macros through Xacro. Using Xacro is key to dynamic and automated changes to our Urdf files. A current status update is that the code is made and I am making a dev environment to test it. Once we simulate the wheels, as POL, we can start creating a frame. We would make joints between the frame and the wheels to get an object that can move. With Xacro we should only need to make small changes but keep the structure of the URDF made the same.

**Comment by abarnes6** [comment]
https://github.com/david-dorf/ExportURDF
